version: "3.8"
services:
  client:
    build: ./client/
    container_name: l7_client
    volumes:
      - webapp:/build
      - ./client/benford:/src
    command: yarn serve 
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    volumes:
      - ./postgres/fixtures.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./postgres/dump:/dump
    container_name: l7_postgres
    env_file:
      - l7.env
  server:
    depends_on:
      - client
      - postgres
    build: ./server/
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - webapp:/app/dist
    container_name: l7_server
    command: ["gunicorn", "-w 1", "-b :8000", "wsgi:app", "--reload"]
    env_file:
      - l7.env
volumes:
  webapp:
